const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Wall: 0},
	{TileMovement: 0},
	{Player: 0},
	{TimeCounter: 0},
	{Range: 0},
	{Flash: 0},
	{Timer: 0},
	{Bomb: 0},
	{Keyboard: 0},
	{BreakableWall: 0},
	{Ground: 0},
	{Direction: 0},
	{Enemy: 0},
	{Tween: 0},
	{Flame: 0},
	{Dust: 0},
	{Gamepad: 0},
	{Fade: 0},
	{TextFont: 0},
	{TextBackground: 0},
	{ExplosionRange: 0},
	{XOffset: 0},
	{YOffset: 0}
];

self.InstanceType = {
	Wall: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BreakableWall: class extends self.ISpriteInstance {},
	Ground: class extends self.ITilemapInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Flame: class extends self.ISpriteInstance {},
	Dust: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	TextBackground: class extends self.ITiledBackgroundInstance {}
}